name: habits
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  flutter_heatmap_calendar: ^1.0.5
  fl_chart: ^0.68.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^17.2.2
  numberpicker: ^2.1.2
  timezone: ^0.9.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: 

flutter:
  uses-material-design: true
